/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class utils_external_NativePooler */

#ifndef _Included_utils_external_NativePooler
#define _Included_utils_external_NativePooler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     utils_external_NativePooler
 * Method:    pool
 * Signature: (IIIIIDD[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_utils_external_NativePooler_pool
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jdouble, jdouble, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
